### ISSUE TITLE
Zusätzliche Lizenzinformationen

### ISSUE THREAD

**Issue by KateiRen** [semeif/Teams-Quickstart-Guide-for-Partners#1]
Vielleicht willst du in der _Readme.md_ oder im _docx_ noch den Verweis auf weiterführende Lizenz Informationen einbauen:
- [Microsoft 365 licensing diagrams](https://github.com/AaronDinnage/Licensing)

**Comment by semeif** [comment]
Hallo KateiRen, 

vielen Dank für den Link, hab es im Dokument unter dem Punkt Lizenzen ergänzt.

LG
Sebastian
